name: Publish SDK Packages

on:
  push:
    branches:
      - master
      - develop
      - 'release/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

       - name: Make gradlew executable
         run: chmod +x ./gradlew

       - name: Run Tests
         run: ./gradlew clean lint test

      - name: Publish
        run: ./gradlew clean publish