name: Publish SDK Packages

on:
  push:
    branches:
      - master
      - develop
      - 'release/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

       - name: Run Tests
         run: ./gradlew clean lint test

      - name: Publish
        run: ./gradlew clean publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}